### ISSUE TITLE
Copyright and license headers in source files

### ISSUE THREAD

**Issue by Teknomancer** [Teknomancer/beezer#9]
Currently we have the copyright starting-year and an ending year for the developer names.

However, maintaining the ending year is going to be difficult unless we automate the task each year. As far as copyright is concerned, just mentioning the starting year should be good enough because from a legal stand-point even if no end-year is mentioned, the copyright still holds. I'm not a lawyer, but I'm pretty sure if someone forgot to update the end year for a few years, the copyright doesn't stop applying, in which case it would be preferable to have the starting year.

I also propose shortening the length of the copyright/license header significantly by chopping off the full verbose BSD license and replacing it with SPDX license identifier:  https://spdx.dev/ids/

I think we already have a LICENSE.md in the root of the project, so that just be more than enough to cover it.

In our case it would be: `// SPDX-License-Identifier: BSD-3-Clause` (must be exactly spelled that way)

A complete example:
```
// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2009 Ramshankar (aka Teknomancer)
// Copyright (c) 2011 Chris Roberts
// All rights reserved
```

**Comment by augiedoggie** [comment]
Yeah, I noticed I missed a few copyright updates on a couple files.  Sounds good to me.

**Comment by Teknomancer** [comment]
Thanks. I also will correct the copyright year for the original files since currently 2009 (the year Beezer went open-source) is used but the copyright starts from the time the code was actually written.

Beezer 0.03 was released in 2005: https://web.archive.org/web/20050204040251/bebits.com/app/4069

The actual code is even older and I'll try to dig if I have some backups of the source code from way back then, or just go with 2005 for now for the relevant files. This will be done manually on a per-file basis.

Edit: Beezer 0.01 was released January 21, 2005 https://web.archive.org/web/20050204015129/http://www.bebits.com/appver/4069

**Comment by Teknomancer** [comment]
Found Beezer_0.01 source code backup. "AboutWindow.cpp"'s license header looked like this ("Somebody" was my nick in BeShare ages ago, brings back some memories) :)

```
/*
 *	Beezer
 *	Copyright (c) 2002 Ramshankar (aka Somebody)
 *	See "License.txt" for licensing info.
*/

#include <String.h>
#include <TranslationUtils.h>
#include <Bitmap.h>
#include <Message.h>
#include <Screen.h>
#include <Alert.h>
```

**Comment by Teknomancer** [comment]
Also, z7Archiver contribution was in 2005:

```
/*
 *	Beezer
 *	Copyright (c) 2005 Ramshankar (aka Somebody)
 *	Copyright (c) 2005 Marcin Konicki (aka ahwayakchih)
 *	See "License.txt" for licensing info.
*/
```

Will fix these as well while doing the copyright and license header cleanups.
